### PR TITLE
Feature/cookies tracker

### PR DESCRIPTION
**Pull request by maximoev**
**New Feature: Santa's Calories Counter**

- Add a Counter for eaten cookies
- Save in BD more cookies and show the total with **mock**

### CODE REVIEW

**Review by RVSolutionsplus507 — DISMISSED** [review]
Muy bien!

**Review by RVSolutionsplus507 — APPROVED** [review]
muy bien 2!

**Review by RVSolutionsplus507 — APPROVED** [review]
Listo corregido

**Review by emmanuel-vandyk — APPROVED** [review]
chayane

**Pull request merged**
